name: Terraform Plan and Apply (Auto Approve)

on:
  push:
    paths:
      - "infra/**"
      - ".github/workflows/**"

env:
  TF_VERSION: 1.14.3

jobs:

  plan-and-apply:
    name: Detect Infrastructure Drift
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    steps:
      - uses: actions/checkout@v6

      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init (State Lock Enabled)
        run: |
          terraform init -input=false -reconfigure \
            -backend-config="bucket=${{ secrets.TF_BACKEND_BUCKET }}" \
            -backend-config="key=${{ secrets.TF_BACKEND_KEY }}" \
            -backend-config="region=${{ secrets.TF_BACKEND_REGION }}" \
            -backend-config="use_lockfile=true" \
            -backend-config="encrypt=true"
      
      - name: Set Terraform Variables
        run: |
          echo "TF_VAR_bucket_name=${{ secrets.BUCKET_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_domain_name=${{ secrets.DOMAIN_NAME }}" >> $GITHUB_ENV

      - name: Run Terraform Plan
        run: |
          terraform plan -out tfplan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan
          if-no-files-found: error


      - name: Restore Infra from Code
        run: terraform apply -auto-approve
